// formConfig.js
import * as Yup from "yup";

export const AddSiteinitialValues = {
  site_code: "",
  site_name: "",
  clients: [],
  site_Address: "",
  Site_Status: "",
  bussiness_Type: "",
  Select_machine_type: "",
  supplier: "",
  DRS_Start_Date: "",
  display_name: "",
  Saga_department_code: "",
  Saga_department_name: "",
  Bp_nctt_site_no: "",
  bank_ref: "",
  Report_generation_Status: "",
  Report_date_type: "",
  consider_keyfules_cards: "",
  Fuel_commission_type: "",
  Paper_work_status: "",
  Bunkered_sale_status: "",
  Drs_upload_status: "",
  client_id: "",
  company_id: "",
  lottery_commission: "",
  instant_lottery_commission: "",
  e_code: "",
  paypoint_commission: "",
  cashback_enable: 0,
  shop_commission: 0,
  paidout: 0,
  apply_sc: 0,
  is_reconciled: 0,
  auto_dayend: 0,
  ignore_tolerance: 0,
  d_deduction: 1,
  display_all_sales: 1,
  security_amount: "",
  loomis_status: 0,
  cashback_status: 0,
  fuel_discount: 0,
  vat_summary: 0,
  include_bunkered_sales: 0,
  show_admin_sale: 0,
  send_auto_report: 0,
  consider_fuel_sales: 1,
  shop_sale_file_upload: 1,
  update_tlm_price: 0,
  change_back_date_price: 0,
  to_emails: [],
  cc_emails: [],
  mobile: "",
};

export const AddSitevalidationSchema = Yup.object({
  site_code: Yup.string().required("Site Code is required"),
  site_name: Yup.string()
    .max(150, "Must be 150 characters or less")
    .required("Site Name is required"),
  site_Address: Yup.string().required("Site Address is required"),
  company_id: Yup.string().required("Company is required"),
  Site_Status: Yup.string().required("Site Status is required"),
  display_name: Yup.string().required("Display Name is required"),
  bussiness_Type: Yup.string().required("Business Type is required"),
  consider_keyfules_cards: Yup.string().required(
    "Consider Keyfules Cards is required"
  ),
  supplier: Yup.string().required("Supplier is required"),
  DRS_Start_Date: Yup.string().required("DRS Start Date is required"),
  Select_machine_type: Yup.string().required("Data Import Types is required"),
  Saga_department_code: Yup.string().required("Sage Department Code is required"),
  Saga_department_name: Yup.string().required("Saga Department Name is required"),
  Drs_upload_status: Yup.string().required("Drs Upload Status is required"),
  Bp_nctt_site_no: Yup.string().required("Bp Nctt Site No is required"),
  bank_ref: Yup.string().required("Bank Reference is required"),
  security_amount: Yup.string().required("Security Amount is required"),
  loomis_status: Yup.string().required("Loomis Status is required"),
  cashback_status: Yup.string().required("Cashback Status is required"),
  apply_sc: Yup.string().required("Apply Add Shop is required"),
  is_reconciled: Yup.string().required("Reconciled Data is required"),
  d_deduction: Yup.string().required("Deduct Deduction is required"),
  display_all_sales: Yup.string().required("Display All Sales is required"),
  cashback_enable: Yup.string().required("Cashback Enable is required"),
  update_tlm_price: Yup.string().required("Update TLM Price is required"),
  to_emails: Yup.array()
    .of(Yup.string().email("Invalid email format"))
    .min(1, "At least one email is required"),
});
